server:
  port: 8080

spring:
  application:
    name: rail-tracker-backend
  datasource:
    url: 
    username: 
    password: 
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
