server:
  port: 8080

spring:
  application:
    name: rail-tracker-backend
  datasource:
    url: jdbc:postgresql://ep-rapid-bar-azzsiv75-pooler.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_BGK4PXoYrNL6
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
